### ISSUE TITLE
Znajdź api z ćwiczeniami

### ISSUE THREAD

**Issue by madrimas** [madrimas/siluets#1]

**Comment by wienio** [comment]
Available API:
[Wger Workout manager]( https://wger.de/en/software/api)
First of all you should map muscle available here: [wger muscle API](https://wger.de/api/v2/muscle/)
and then you can ask for particular exercises endpoint: `api/v2/exercise/?muscles=<muscle_id>`
[Here](https://wger.de/api/v2/) you got all available endpoints.
Everything is in JSON format. For example all available muscles response:
```
{
    "count": 15,
    "next": null,
    "previous": null,
    "results": [
        {
            "id": 2,
            "name": "Anterior deltoid",
            "is_front": true
        },
        ...]
}
```
Please check if this meet all requirements
