### ISSUE TITLE
Zaimplementuj tworzenie wykresów przebytych treningów

### ISSUE THREAD

**Issue by madrimas** [madrimas/siluets#4]
Stwórz wykresy:

1. Zmiany wymiarów ciała (wykres kalkulowanego BMI, wagi, obwodów ciała itp. [user może wybierać co chce zobaczyć])
2. Wykres kołowy (pie chart) procentowo wykonywanych ćwiczeń np. (15% klatka, 20% biceps etc.) na podstawie treningów (można opcjonalnie wybrać zakres dat które interesują użytkownika) 
3. Wykres liniowy ciężarów dla wybranego ćwiczenia

**Comment by wienio** [comment]
Wykresy zostały stworzone, implementacja gotowa.
